include_recipe "apt-repo::grml"

include_recipe "my-stuff::inode-ubuntu"
include_recipe "my-stuff::chef"
include_recipe "my-stuff::multimedia"
include_recipe "my-stuff::virt"
include_recipe "my-stuff::useful-stuff"
include_recipe "my-stuff::unattended-upgrades"
include_recipe "my-stuff::internet-stuff"
include_recipe "my-stuff::dropbox"
include_recipe "my-stuff::google-stuff"
include_recipe "my-stuff::my-users"
